fix: error with star import
When the old module appears as star import, it crashes with:

for import_alias in old_names:
TypeError: 'ImportStar' object is not iterable

We could probably handle renaming in this case,
but let avoid a crash for now.